create extension if not exists pgcrypto;

create table if not exists public.wallets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  wallet_address text not null,
  created_at timestamptz not null default now(),
  last_login timestamptz not null default now(),
  constraint wallets_wallet_address_unique unique (wallet_address)
);

create index if not exists wallets_user_id_idx
on public.wallets (user_id);

create index if not exists wallets_wallet_address_lower_idx
on public.wallets (lower(wallet_address));

create table if not exists public.staking_posts (
  id bigint generated by default as identity primary key,
  "user" uuid,
  author_id uuid,
  author_name text,
  title text,
  content text,
  content_excerpt text,
  category text not null default '',
  staking text,
  value text,
  live boolean not null default false,
  "delete" boolean not null default false,
  type text not null default 'stake_backed_post',
  status text,
  actor_type text,
  posted_by text,
  agent_wallet text,
  acceptance_criteria text,
  tags jsonb not null default '[]'::jsonb,
  budget text,
  deadline timestamptz,
  visibility_mode text not null default 'public',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint staking_posts_staking_unique unique (staking),
  constraint staking_posts_visibility_mode_check
    check (visibility_mode in ('public', 'login_required', 'paid_full_text'))
);

create index if not exists staking_posts_user_idx
on public.staking_posts ("user");

create index if not exists staking_posts_author_id_idx
on public.staking_posts (author_id);

create index if not exists staking_posts_category_live_idx
on public.staking_posts (category, live, "delete", id desc);

create index if not exists staking_posts_staking_idx
on public.staking_posts (staking);

create table if not exists public.agent_memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  login_type text not null,
  wallet_address text,
  memory_text text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_memories_user_id_unique unique (user_id),
  constraint agent_memories_login_type_check
    check (login_type in ('wallet', 'twitter'))
);

create index if not exists agent_memories_wallet_address_lower_idx
on public.agent_memories (lower(wallet_address));

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_staking_posts_updated_at on public.staking_posts;
create trigger set_staking_posts_updated_at
before update on public.staking_posts
for each row
execute function public.set_updated_at();

drop trigger if exists set_agent_memories_updated_at on public.agent_memories;
create trigger set_agent_memories_updated_at
before update on public.agent_memories
for each row
execute function public.set_updated_at();

create table if not exists public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  requester_label text not null default 'CAW-linked user',
  status text not null default 'queued',
  goal text not null,
  category text not null default 'signals',
  stake_amount text not null default '0.005',
  visibility_mode text not null default 'public',
  acceptance_criteria text,
  tags jsonb not null default '[]'::jsonb,
  agent_wallet text,
  pact_id text,
  approve_request_id text,
  approve_tx text,
  deposit_request_id text,
  deposit_tx text,
  post_id bigint references public.staking_posts(id),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_runs_status_check
    check (status in ('queued', 'executing', 'verified', 'failed')),
  constraint agent_runs_visibility_mode_check
    check (visibility_mode in ('public', 'login_required', 'paid_full_text'))
);

create index if not exists agent_runs_status_created_idx
on public.agent_runs (status, created_at desc);

create index if not exists agent_runs_post_id_idx
on public.agent_runs (post_id);

drop trigger if exists set_agent_runs_updated_at on public.agent_runs;
create trigger set_agent_runs_updated_at
before update on public.agent_runs
for each row
execute function public.set_updated_at();
